# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-stretch-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: "root"
          DB_PASSWORD: ""
      - image: circleci/mysql:8.0.16-ram
        command: |
          mysqld --default-authentication-plugin=mysql_native_password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: toilet-very-nice_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ROOT_HOST: '%'
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.2
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

      # Run rubocop
      - run:
          name: rubocop
          command: bundle exec rubocop
