# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          TZ: Asia/Tokyo
          BUNDLER_VERSION: 2.0.2
      - image: circleci/mysql:8.0.16
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        keys:
          - gem-cache-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /bin/bundle
            sudo rm /bin/bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: gem-cache-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      # # Rspec
      # - run:
      #     name: Rspec
      #     command: bundle exec rspec
      # # Run rubocop
      # - run:
      #     name: rubocop
      #     command: bundle exec rubocop
